### ISSUE TITLE
Identifiers longer then 30 characters - compile error on older DB versions or campatibility settings

### ISSUE THREAD

**Issue by NikoHorn** [ogobrecht/plex#12]
Unable to install PLEX due to PLS-00114 (Package PLEX) during installation of PLEX on DB Version 12.2.0.1 with compatible set to 12.1.

**Comment by ogobrecht** [comment]
Hi Niko,

sorry, I forgot to check the identifier length of two relatively new procedures. Obviously, my development system has a max identifier length of 128. Sorry again. I will fix it immediately.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Niko,

should work now. Please download the [latest version](https://github.com/ogobrecht/plex/releases/latest) (currently 2.4.2) and let me know if you are now successful with your installation. I have currently no old test database available in such a short time.

Best regards
Ottmar

**Comment by NikoHorn** [comment]
Hi Ottmar,

that was quite fast. Will try it. -> Works!

Thanks.

Best Regards
Niko
